/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.DefaultHandler;
import org.eclipse.jetty.server.handler.HandlerList;
import org.eclipse.jetty.server.handler.ResourceHandler;

public class App {
    public static void main(String[] args) throws Exception {
        Server server = new Server(8080);
        ResourceHandler resourceHandler = new ResourceHandler();
        String staticFiles = App.class.getClassLoader().getResource("resources/ui").toExternalForm();
        resourceHandler.setResourceBase(staticFiles);
        resourceHandler.setDirectoriesListed(true);
        HandlerList handlers = new HandlerList();
        handlers.setHandlers(new Handler[] { resourceHandler, new DefaultHandler() });
        server.setHandler(handlers);
        server.start();
        server.join();
    }
}
