VERSION 0.6
FROM gradle:7.5.1-jdk17
WORKDIR /app/javaApp

deps:
    COPY app/build.gradle.kts ./app/
    COPY --dir gradle ./
    COPY gradlew settings.gradle.kts ./
    RUN ./gradlew dependencies

build:
    FROM +deps
    COPY --dir app/src ./app/src
    COPY ../mnist+build/saved_model ../mnist/saved_model
    COPY ../todo+build/build ../todo/build
    RUN ls /app
    RUN ls /app/mnist
    RUN ls /app/todo
    RUN ./gradlew build
    SAVE ARTIFACT ./app/build/libs/app.jar AS LOCAL app.jar
