name: Earthly build

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.21/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci -a +build/app.jar
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu
        path: app.jar
  build-macos:
    runs-on: macos-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - name: Install docker
      run: "brew install docker"
    - name: Download latest earthly
      run: "brew install earthly/earthly/earthly && earthly bootstrap"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci -a +build/app.jar
    - uses: actions/upload-artifact@v3
      with:
        name: macos
        path: app.jar
  build-windows:
    runs-on: windows-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - uses: Vampire/setup-wsl@v1
    - name: Show folder before download
      run: dir
    - name: Download latest earthly
      run: "curl -o earthly.exe https://github.com/earthly/earthly/releases/download/v0.6.21/earthly-windows-amd64.exe"
    - name: Show folder after download
      run: dir
    - name: Earthly version
      run: earthly.exe --version
    - name: Run build
      run: earthly.exe --ci -a +build/app.jar
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: app.jar
